worker_processes  1;

error_log  "../../logs/nginx_error.log";

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log  "../../logs/nginx_access.log";

    sendfile        on;
    keepalive_timeout  65;

    server {
        include "../../../listen.conf";
        server_name  localhost;

        include "../../../public.conf";
        include "../../../rewrite.conf";

        location ~ \.php$ {
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
            
            # Use absolute path resolving from document_root
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }
    }
}
